# Generated by Django 4.2.3 on 2023-07-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
    ]
