"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path, os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5#*92*2kzt1(vu2%d39uaaghwso5dx(8$e+@54a^5v-ur^d6ik'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'blog',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'anymail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 以下のdirsに入力されたtemplatesフォルダーを最初に探しにいく
        # 次にinstalled_appの中身を探しにいく
        # djangoは同じURLがあった場合先に見つけたURLを表示する性質があるため
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# 全体からstaticディレクトリを探す。パスはリストで設定をする
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# 以下はターミナルにメッセージが送信される使用のため実際のメアドへ送信する場合はコメントアウトもしくは削除
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

LOGIN_URL ='/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODELはプロジェクト全体で使用するユーザーで、blog.Userがblogアプリの中のmodels.pyのUserというモデルを参照
AUTH_USER_MODEL = 'blog.User'

FRONTEND_URL = 'http://127.0.0.1:8000/'

ANYMAIL = {
    "MAILGUN_API_KEY": '103278aa2c9a212ef84250f2a5acb1c2-c30053db-b5c6e6c3',
    "MAILGUN_SENDER_DOMAIN": 'sandbox3f8ccde9d08e443da3ca9754e3e8d20b.mailgun.org',
}
# メールガンのバックエンドを使用する
EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'

# 送信元をユーザーに表示するメアドの設定。
DEFAULT_FROM_EMAIL = 'yocchantaku0127@gmail.com'
# システムやサーバーに不具合が発生した際に管理者に送られる送信元のメアド（ユーザーには表示されない）
SERVER_EMAIL = 'server@example.com'
